version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 4000:5000
  volumes:
  - ./:/app

 mysqldb:
  image: mysql
  ports:
  - 3360:3306
  environment:
  - MYSQL_ROOT_PASSWORD=password
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: